"""initial schema

Revision ID: cb31a1753293
Revises: 
Create Date: 2026-06-23 22:48:47.313306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'cb31a1753293'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('value', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_settings_id'), 'settings', ['id'], unique=False)
    op.create_index(op.f('ix_settings_key'), 'settings', ['key'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'USER', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('leads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('normalized_name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=60), nullable=True),
    sa.Column('normalized_phone', sa.String(length=40), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('state', sa.String(length=2), nullable=True),
    sa.Column('segment', sa.String(length=120), nullable=True),
    sa.Column('category', sa.String(length=160), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('website_url', sa.String(length=500), nullable=True),
    sa.Column('google_maps_url', sa.String(length=1000), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('review_count', sa.Integer(), nullable=True),
    sa.Column('digital_presence', sa.Enum('SEM_SITE', 'SITE_RUIM', 'SITE_OK', 'SITE_DESCONHECIDO', name='digitalpresence'), nullable=False),
    sa.Column('potential_score', sa.Integer(), nullable=False),
    sa.Column('potential_level', sa.Enum('BAIXO', 'MEDIO', 'ALTO', name='potentiallevel'), nullable=False),
    sa.Column('current_status', sa.Enum('NOVO', 'A_CONTATAR', 'CONTATADO', 'NAO_RESPONDEU', 'INTERESSADO', 'PROPOSTA_ENVIADA', 'FECHADO', 'PERDIDO', 'NAO_CONTATAR', name='leadstatus'), nullable=False),
    sa.Column('assigned_to_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('google_maps_url', name='uq_leads_google_maps_url'),
    sa.UniqueConstraint('normalized_name', 'city', 'normalized_phone', name='uq_leads_normalized_identity')
    )
    op.create_index(op.f('ix_leads_city'), 'leads', ['city'], unique=False)
    op.create_index(op.f('ix_leads_current_status'), 'leads', ['current_status'], unique=False)
    op.create_index(op.f('ix_leads_google_maps_url'), 'leads', ['google_maps_url'], unique=False)
    op.create_index(op.f('ix_leads_id'), 'leads', ['id'], unique=False)
    op.create_index(op.f('ix_leads_name'), 'leads', ['name'], unique=False)
    op.create_index(op.f('ix_leads_normalized_name'), 'leads', ['normalized_name'], unique=False)
    op.create_index(op.f('ix_leads_normalized_phone'), 'leads', ['normalized_phone'], unique=False)
    op.create_index(op.f('ix_leads_segment'), 'leads', ['segment'], unique=False)
    op.create_index(op.f('ix_leads_state'), 'leads', ['state'], unique=False)
    op.create_table('search_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=False),
    sa.Column('state', sa.String(length=2), nullable=False),
    sa.Column('segment', sa.String(length=120), nullable=False),
    sa.Column('max_results', sa.Integer(), nullable=False),
    sa.Column('prioritize_without_site', sa.Boolean(), nullable=False),
    sa.Column('prioritize_with_phone', sa.Boolean(), nullable=False),
    sa.Column('include_bad_websites', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELED', 'REQUIRES_MANUAL_REVIEW', name='searchjobstatus'), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('found_count', sa.Integer(), nullable=False),
    sa.Column('saved_count', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('cancel_requested', sa.Boolean(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_search_jobs_city'), 'search_jobs', ['city'], unique=False)
    op.create_index(op.f('ix_search_jobs_id'), 'search_jobs', ['id'], unique=False)
    op.create_index(op.f('ix_search_jobs_segment'), 'search_jobs', ['segment'], unique=False)
    op.create_index(op.f('ix_search_jobs_state'), 'search_jobs', ['state'], unique=False)
    op.create_index(op.f('ix_search_jobs_status'), 'search_jobs', ['status'], unique=False)
    op.create_table('lead_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.Enum('NOTE', 'STATUS_CHANGE', 'CONTACT_ATTEMPT', 'MANUAL_UPDATE', name='leadeventtype'), nullable=False),
    sa.Column('old_status', sa.Enum('NOVO', 'A_CONTATAR', 'CONTATADO', 'NAO_RESPONDEU', 'INTERESSADO', 'PROPOSTA_ENVIADA', 'FECHADO', 'PERDIDO', 'NAO_CONTATAR', name='leadstatus'), nullable=True),
    sa.Column('new_status', sa.Enum('NOVO', 'A_CONTATAR', 'CONTATADO', 'NAO_RESPONDEU', 'INTERESSADO', 'PROPOSTA_ENVIADA', 'FECHADO', 'PERDIDO', 'NAO_CONTATAR', name='leadstatus'), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lead_events_id'), 'lead_events', ['id'], unique=False)
    op.create_table('search_job_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('search_job_id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.Enum('CREATED', 'UPDATED', 'DUPLICATE', 'SKIPPED', 'FAILED', name='searchresultaction'), nullable=False),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.ForeignKeyConstraint(['search_job_id'], ['search_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_search_job_results_id'), 'search_job_results', ['id'], unique=False)
    op.create_table('site_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('website_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('SEM_SITE', 'SITE_RUIM', 'SITE_OK', 'ERRO', name='siteanalysisstatus'), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('issues', sa.JSON(), nullable=False),
    sa.Column('analysis_data', sa.JSON(), nullable=False),
    sa.Column('manual_override_status', sa.Enum('SEM_SITE', 'SITE_RUIM', 'SITE_OK', 'ERRO', name='siteanalysisstatus'), nullable=True),
    sa.Column('manual_override_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_site_analyses_id'), 'site_analyses', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_site_analyses_id'), table_name='site_analyses')
    op.drop_table('site_analyses')
    op.drop_index(op.f('ix_search_job_results_id'), table_name='search_job_results')
    op.drop_table('search_job_results')
    op.drop_index(op.f('ix_lead_events_id'), table_name='lead_events')
    op.drop_table('lead_events')
    op.drop_index(op.f('ix_search_jobs_status'), table_name='search_jobs')
    op.drop_index(op.f('ix_search_jobs_state'), table_name='search_jobs')
    op.drop_index(op.f('ix_search_jobs_segment'), table_name='search_jobs')
    op.drop_index(op.f('ix_search_jobs_id'), table_name='search_jobs')
    op.drop_index(op.f('ix_search_jobs_city'), table_name='search_jobs')
    op.drop_table('search_jobs')
    op.drop_index(op.f('ix_leads_state'), table_name='leads')
    op.drop_index(op.f('ix_leads_segment'), table_name='leads')
    op.drop_index(op.f('ix_leads_normalized_phone'), table_name='leads')
    op.drop_index(op.f('ix_leads_normalized_name'), table_name='leads')
    op.drop_index(op.f('ix_leads_name'), table_name='leads')
    op.drop_index(op.f('ix_leads_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_google_maps_url'), table_name='leads')
    op.drop_index(op.f('ix_leads_current_status'), table_name='leads')
    op.drop_index(op.f('ix_leads_city'), table_name='leads')
    op.drop_table('leads')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_settings_key'), table_name='settings')
    op.drop_index(op.f('ix_settings_id'), table_name='settings')
    op.drop_table('settings')
    # ### end Alembic commands ###
